const ProductActionTypes = {
  PRODUCT_FETCH_START: "PRODUCT_FETCH_START",
  PRODUCT_FETCH_SUCCESS: "PRODUCT_FETCH_SUCCESS",
  PRODUCT_FETCH_FAILURE: "PRODUCT_FETCH_FAILURE",
};

export default ProductActionTypes;
